-- 게시판 3-스택(JPA/jOOQ/Spring Data JDBC) 공유 물리 스키마.
-- 운영 모범사례: 엔티티 자동 DDL(ddl-auto=create/update) 금지 → Flyway 로 버전 관리하고 ddl-auto=validate 로
-- 엔티티↔스키마 정합만 검증한다(DB_LAYER_GUIDE 2·5장). 타입은 H2·PostgreSQL 공통 이식형으로 작성:
--   * bigint generated by default as identity  (H2·PG10+ 공통 IDENTITY)
--   * timestamp(6) with time zone              (H2·PG(timestamptz) 공통, Instant(UTC) 매핑과 정합)
--   * varchar(n)                               (공통)
-- 세 스택이 같은 테이블을 공유하므로(H2 CASE_INSENSITIVE_IDENTIFIERS), 컬럼 정의는 JPA 엔티티 기준과 1:1 이다.

create table board_post (
    id         bigint generated by default as identity primary key,
    title      varchar(200)   not null,
    content    varchar(20000) not null,
    author     varchar(50)    not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    version    bigint         not null   -- 낙관적 락(@Version)
);

create table board_like (
    id         bigint generated by default as identity primary key,
    post_id    bigint       not null,
    author     varchar(50)  not null,
    created_at timestamp(6) with time zone not null,
    constraint uq_board_like_post_author unique (post_id, author),   -- 사용자당 1회(멱등 좋아요)
    constraint fk_board_like_post foreign key (post_id) references board_post (id)
);

create table board_comment (
    id         bigint generated by default as identity primary key,
    post_id    bigint        not null,
    author     varchar(50)   not null,
    content    varchar(1000) not null,
    created_at timestamp(6) with time zone not null,
    constraint fk_board_comment_post foreign key (post_id) references board_post (id)
);

-- 목록/댓글 조회는 post_id 로 자주 필터링하므로 보조 인덱스를 둔다(운영급 관습).
create index ix_board_like_post on board_like (post_id);
create index ix_board_comment_post on board_comment (post_id);
