-- 영속성 감사(persistence) 데모 엔티티 sample_note 의 스키마.
-- BaseEntity(@MappedSuperclass) 의 감사 컬럼(created_at/updated_at/created_by/updated_by)을 포함한다.
-- created_by/updated_by 는 TraceContextAuditorAware 가 인증 사용자(X-User-Id)를 자동 기록한다(nullable — 미인증 허용).
-- 감사 시각은 Instant(UTC) → timestamp with time zone(H2·PG 공통).

create table sample_note (
    id         bigint generated by default as identity primary key,
    text       varchar(255),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    created_by varchar(64),
    updated_by varchar(64)
);
