package ai.mutuus.sample.demo;

import java.util.List;
import java.util.Map;

import javax.sql.DataSource;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * DB 랩 페이지의 <b>CRUD</b> 를 <b>앱의 실제(@Primary) DataSource</b> 로 수행한다(ai=H2, local=실 PostgreSQL).
 * 테이블 {@code lab_item(id, name UNIQUE NOT NULL, qty)} 에 대해 실제 insert/select/update/delete 를 하고,
 * 제약 위반(중복 name)·미존재 id·트랜잭션 롤백 등 오류 동작도 실 DB 로 재현한다.
 */
@Component
public class DbLabSupport {

    private final JdbcTemplate jdbc;
    private volatile boolean ready;

    public DbLabSupport(DataSource dataSource) {
        this.jdbc = new JdbcTemplate(dataSource);
    }

    private synchronized void ensureTable() {
        if (ready) {
            return;
        }
        // H2·PostgreSQL 공통 문법(표준 IDENTITY). name 은 UNIQUE + NOT NULL 로 제약 위반 시연.
        jdbc.execute("create table if not exists lab_item ("
                + "id bigint generated by default as identity primary key, "
                + "name varchar(100) not null unique, "
                + "qty int not null default 0)");
        ready = true;
    }

    /** Create — 생성된 id 반환. name 중복이면 DataIntegrityViolationException(→ 컨트롤러 409). */
    public Map<String, Object> create(String name, int qty) {
        ensureTable();
        KeyHolder kh = new GeneratedKeyHolder();
        jdbc.update(con -> {
            var ps = con.prepareStatement("insert into lab_item(name, qty) values(?, ?)", new String[]{"id"});
            ps.setString(1, name);
            ps.setInt(2, qty);
            return ps;
        }, kh);
        Number id = kh.getKey();
        return get(id == null ? -1 : id.longValue());
    }

    /** Read all. */
    public List<Map<String, Object>> list() {
        ensureTable();
        return jdbc.queryForList("select id, name, qty from lab_item order by id");
    }

    /** Read one — 없으면 null. */
    public Map<String, Object> get(long id) {
        ensureTable();
        List<Map<String, Object>> rows =
                jdbc.queryForList("select id, name, qty from lab_item where id = ?", id);
        return rows.isEmpty() ? null : rows.get(0);
    }

    /** Update — 영향 행 수(0이면 미존재 → 컨트롤러 404). */
    public int update(long id, String name, int qty) {
        ensureTable();
        return jdbc.update("update lab_item set name = ?, qty = ? where id = ?", name, qty, id);
    }

    /** Delete — 영향 행 수(0이면 미존재 → 컨트롤러 404). */
    public int delete(long id) {
        ensureTable();
        return jdbc.update("delete from lab_item where id = ?", id);
    }

    public int countByName(String name) {
        ensureTable();
        Integer n = jdbc.queryForObject("select count(*) from lab_item where name = ?", Integer.class, name);
        return n == null ? 0 : n;
    }

    /**
     * 트랜잭션 롤백 시연: insert 후 예외를 던진다. {@code @Transactional} 이므로 커밋되지 않고 롤백된다
     * (컨트롤러가 이 메서드를 프록시 경유로 호출해야 트랜잭션이 적용됨 — 자기호출 금지).
     */
    @Transactional
    public void insertThenFail(String name, int qty) {
        ensureTable();
        jdbc.update("insert into lab_item(name, qty) values(?, ?)", name, qty);
        throw new IllegalStateException("의도적 예외 — 트랜잭션 롤백 유도");
    }
}
