spring.application.name=sample-batch
spring.main.banner-mode=off
mutuus.common.service-name=sample-batch
mutuus.common.service-short-name=batch
mutuus.common.logging.environment=local
mutuus.common.logging.directory=target/logs
